<?php

/**
 * @file
 * Custom Event Registration module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_mail().
 */
function event_registration_mail($key, &$message, $params) {
  $message['from'] = \Drupal::config('system.site')->get('mail');

  switch ($key) {

    case 'user_confirmation':
      $message['subject'] = t('Event Registration Confirmation');
      $message['body'][] = $params['message'];
      break;

    case 'admin_notification':
      $message['subject'] = t('New Event Registration Received');
      $message['body'][] = $params['message'];
      break;
  }
}
